services:
  invoices-pg:
    image: postgres
    container_name: postgres-invoives
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: invoices
    ports:
      - "5483:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d








 